### ISSUE TITLE
Should not echo password to stdout

### ISSUE THREAD

**Issue by chrisegner** [joeledwards/node-wait-for-postgres#6]
The database password is logged to stdout, which may be attached subsequently fed into a logging system.

https://github.com/joeledwards/node-wait-for-postgres/blob/master/src/index.coffee#L31

**Comment by joeledwards** [comment]
I have corrected this (now always prints as *** in the URI), and it has been published as 1.5.3

**Comment by chrisegner** [comment]
I haven't had a chance to pull and test the code yet, but I believe there's a typo (s/url/uri/ at line 29).

Also, the approach should work in most cases, but is less safe than it could be.  Replace only replaces the first instance, so this could leak bad passwords like the following:

```
> 'postgres://projectName:projectName@projectName-01.vpc.company.com:5432/projectName'.replace('projectName', '***')
'postgres://***:projectName@projectName-01.vpc.company.com:5432/projectName'
```

Note that the username in this case was replaced instead of the password, revealing the password.  It's probably best to construct the masked URI again, only with `#{password}` replaced by `***`.

**Comment by chrisegner** [comment]
Also, thanks for the quick response, @joeledwards!

**Comment by joeledwards** [comment]
Hi @chrisegner , I quickly realized the issue with my approach last night, and corrected it. The issue was that I forgot to push my corrected approach. I have pushed it now. Let me know if you have suggestions for improvement, or if you like the change.

Thanks!
Joel
